permissions:
  contents: write
  packages: write
on:
  workflow_run:
    workflows:
      - mekadbms - build - bin
    branches: [main]
    types:
      - completed
  workflow_dispatch:
    inputs:
      commit:
        type: string
        description: The commit that produced the release this workflow should run on
env:
  REGISTRY_IMAGE: hypi/mekadbms

# If new code is pushed to a PR branch, then cancel in progress workflows for that PR.
# Ensures that we don't waste CI time, and returns results quicker
# https://github.com/jonhoo/rust-ci-conf/pull/5
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: false

name: mekadbms - build - docker
jobs:
  build_docker_images:
    name: ${{ matrix.platform.os_name }} with rust ${{ matrix.toolchain }}
    runs-on: ${{ matrix.platform.os }}
    if: ${{ github.event.workflow_run.conclusion == 'success' || inputs.commit}}
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os_name: Linux-aarch64
            os: ubuntu-latest
            #hf = hard float i.e. where the CPU includes floating point support
            target: aarch64-unknown-linux-gnu
            docker_target: linux/arm64
            bin: mekadbms-linux-arm64
            command: build
          - os_name: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            #            target: x86_64-unknown-linux-musl
            docker_target: linux/amd64
            bin: mekadbms-linux-amd64
            command: build
          - os_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: mekadbms-amd64.exe
            docker_target: windows/amd64
            command: both
          #https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
          - os_name: macOS-x86_64
            #13 is intel/x86
            os: macos-13
            target: x86_64-apple-darwin
            docker_target: linux/amd64
            bin: mekadbms-darwin-amd64
            command: both
          - os_name: macOS-aarch64
            #macos-14 is arm64/M1
            os: macOS-14
            target: aarch64-apple-darwin
            docker_target: linux/arm64
            bin: mekadbms-darwin-arm64
            command: both
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.CROSS_REPO_TOKEN }}
          #defaults to '' if inputs.commit is not set (when triggered automatically)
          ref: ${{ inputs.commit }}
      #Configure git to auth with the cross repo PAT
      - run: git config --global url."https://${{ secrets.CROSS_REPO_TOKEN }}@github.com".insteadOf ssh://git@github.com
      #      - run: git config --global url."https://${{ secrets.CROSS_REPO_TOKEN }}@github.com".insteadOf https://github.com

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: type=raw,value={{branch}}-{{sha}}

      - name: Download binary from GitHub
        working-directory: mekadb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir mekadb/target/${{ matrix.platform.target }}/release
          gh release download ${{ steps.meta.outputs.version }} \
          --dir mekadb/target/${{ matrix.platform.target }}/release \
          --pattern "${{ matrix.platform.bin }}" \
          --clobber
          ls -hl mekadb/target/${{ matrix.platform.target }}/release

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - uses: actions/checkout@v4
#        with:
#          submodules: recursive
#          token: ${{ secrets.CROSS_REPO_TOKEN }}
#
#      - name: Docker meta
#        id: meta
#        uses: docker/metadata-action@v5
#        with:
#          images: ${{ env.REGISTRY_IMAGE }}
#          tags: type=raw,value={{branch}}-{{sha}}
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Create manifest list and push
#        working-directory: /tmp/digests
#        run: |
#          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
#            $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)
#
#      - name: Inspect image
#        run: |
#          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}
#
#      - uses: actions/checkout@v4
#        with:
#          submodules: recursive
#          token: ${{ secrets.CROSS_REPO_TOKEN }}
#
#      - name: Tag and push
#        run: |
#          git config --global user.email "github-action@hypi.io"
#          git config --global user.name "Hypi Github Action"
#          git tag ${{ steps.meta.outputs.version }}
#          git pull origin $(git rev-parse --abbrev-ref HEAD)
#          git push origin $(git rev-parse --abbrev-ref HEAD)
#          git push origin --tags
