permissions:
  contents: write
  packages: write
on:
  workflow_run:
    workflows:
      - mekadbms - create draft release
    branches: [main]
    types:
      - completed
  workflow_dispatch:
#on:
#  push:
#    branches:
#      - main
#    #    - feature/vitess
#    paths-ignore:
#      - clients/**
#  pull_request:
#  workflow_dispatch:
env:
  REGISTRY_IMAGE: hypi/mekadbms

# If new code is pushed to a PR branch, then cancel in progress workflows for that PR.
# Ensures that we don't waste CI time, and returns results quicker
# https://github.com/jonhoo/rust-ci-conf/pull/5
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: false

name: mekadbms - build - bin
jobs:
  build:
    name: ${{ matrix.platform.os_name }} with rust ${{ matrix.toolchain }}
    runs-on: ${{ matrix.platform.os }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    #if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        platform:
#          - os_name: Linux-aarch64
#            os: ubuntu-latest
##            target: aarch64-unknown-linux-musl
#            #hf = hard float i.e. where the CPU includes floating point support
#            target: arm-unknown-linux-gnueabihf
#            docker_target: linux/arm64
#            bin: mekadbms-linux-arm64
#            command: build
          - os_name: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
#            target: x86_64-unknown-linux-musl
            docker_target: linux/amd64
            bin: mekadbms-linux-amd64
            command: build
#          - os_name: Windows-x86_64
#            os: windows-latest
#            target: x86_64-pc-windows-msvc
#            bin: mekadbms-amd64.exe
#            docker_target: windows/amd64
#            command: both
#          - os_name: macOS-x86_64
#            os: macOS-latest
#            target: x86_64-apple-darwin
#            docker_target: linux/amd64
#            bin: mekadbms-darwin-amd64
#            command: both
#          - os_name: macOS-aarch64
#            os: macOS-latest
#            target: aarch64-apple-darwin
#            docker_target: linux/arm64
#            bin: mekadbms-darwin-arm64
#            command: both
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.CROSS_REPO_TOKEN }}
      #Configure git to auth with the cross repo PAT
      - run: git config --global url."https://${{ secrets.CROSS_REPO_TOKEN }}@github.com".insteadOf ssh://git@github.com
      #      - run: git config --global url."https://${{ secrets.CROSS_REPO_TOKEN }}@github.com".insteadOf https://github.com

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: type=raw,value={{branch}}-{{sha}}

      - name: Set up QEMU
        if: ${{ !contains(matrix.platform.docker_target, 'linux/amd64') }}
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: Swatinem/rust-cache@v2

      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          version: "25.x"

      - name: Install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          targets: ${{ matrix.platform.target }}

      - name: cargo generate-lockfile
        # enable this ci template to run regardless of whether the lockfile is checked in or not
        if: hashFiles('Cargo.lock') == ''
        working-directory: mekadb
        run: cargo generate-lockfile

        #      - name: start opensearch
        #        run: docker compose up -d --wait
        #
        #      #it'll start before
        #      - name: Wait for Opensearch to start
        #        run: sleep 10

        #Use rustup target list to get full list of rust targets
        #docker:26.1.3-dind is available for amd64,arm64,arm/v6,arm/v7
        #See for linker export https://github.com/rust-lang/rust/issues/28924#issuecomment-580828030
      - name: build linux X86
        if: contains(matrix.platform.docker_target, 'linux/amd64')
        working-directory: mekadb
        #x86_64-unknown-linux-gnu is default on Ubuntu so no need to install it
        #rustup toolchain install ${{ matrix.toolchain }}-${{ matrix.platform.target }}
        run: |
          rustup show
          export RUSTFLAGS="-C target-feature=+crt-static"
          cargo build --release --package mekadbms --target ${{ matrix.platform.target }}

      - name: build linux/mac ARM
        if: contains(matrix.platform.os_name, 'aarch64')
        working-directory: mekadb
        #necessary or we get "jammy-updates/restricted amd64 Packages " errors from update
        #sudo rm -f /etc/apt/sources.list.d/archive_uri-*
        #see https://github.com/actions/runner-images/issues/5656
        #we symlink /usrarm-linux-* .so.<N> files to /lib because rustc looks for them there and ignores LD_LIBRARY_PATH env - clue from https://stackoverflow.com/a/52832543/400048
        #clues from about ubuntu deps https://groups.google.com/g/linux.debian.bugs.dist/c/6P4cw8mMwO4
        #same from https://askubuntu.com/a/250721/10273
        #and https://askubuntu.com/a/676704/10273
        #didn't work but was useful https://unix.stackexchange.com/a/751333/4489
        #linker options from https://blog.rust-lang.org/2016/05/13/rustup.html
        #rm -rf ~/.cargo/registry/index because after installing arm old deps appear corrupt? https://stackoverflow.com/a/69499185/400048
        #rm -rf ~/.cargo/registry - only seems to be via rustup https://stackoverflow.com/a/41093785/400048
        #cargo vendor is necessary because when cargo is run after arm dependencies are installed, it fails to resolve the git dependency we have
        run: |
          set -e
          set -o xtrace
          cargo update --verbose && \
          cargo vendor >> .cargo/config.toml && \
          cat .cargo/config.toml && \
          sudo rm -f /etc/apt/sources.list.d/archive* && \
          sudo dpkg --add-architecture arm64 && \
          sudo apt-get -y update || true && \
          sudo apt-get -y install \
                      gcc-arm-linux-gnueabihf \
                      g++-arm-linux-gnueabihf \
                      libc6-armhf-cross \
                      libssl-dev  && \
          ls -ahl /usr/arm-linux-gnueabihf/lib && \
          export CC=arm-linux-gnueabihf-gcc && \
          export CARGO_TARGET_ARM_UNKNOWN_LINUX_GNUEABIHF_LINKER=/usr/bin/arm-linux-gnueabihf-gcc && \
          export RUSTFLAGS="-L=/usr/arm-linux-gnueabihf/lib -C target-feature=+crt-static" && \
          rustup toolchain install ${{ matrix.toolchain }}-${{ matrix.platform.target }} && \
          rustup show && \
          for filename in "/usr/arm-linux-gnueabihf/lib/"*.so.*; do sudo ln -s "$filename" "/lib/$(basename $filename)"; done && \
          rm -rf ~/.cargo/registry/index && \
          rm -rf ~/.cargo/registry && \
          rm -rf ~/.cargo/git && \
          cargo build --verbose --release --package mekadbms --target ${{ matrix.platform.target }}

        #https://github.com/aws/aws-lc/issues/1477
        #https://github.com/rustls/rustls/issues/1913
        #nasm isn't added to path so need to do it manually https://github.com/chocolatey/choco/issues/2794
        #https://aws.github.io/aws-lc-rs/requirements/windows.html
      #          set PATH="C:\Program Files\NASM;%PATH%"
      #          set AWS_LC_SYS_NO_ASM="true"
      - uses: ilammy/setup-nasm@v1
        if: matrix.platform.os_name == 'Windows-x86_64'
        #Use rustup target list to get full list of rust targets
        #docker:26.1.3-dind is available for amd64,arm64,arm/v6,arm/v7
        #See for linker export https://github.com/rust-lang/rust/issues/28924#issuecomment-580828030
      - name: build (windows)
        if: matrix.platform.os_name == 'Windows-x86_64'
        working-directory: mekadb
        run: |
          rustup toolchain install ${{ matrix.toolchain }}-${{ matrix.platform.target }}
          rustup show
          cargo build --release --package mekadbms --target ${{ matrix.platform.target }}

      - name: Rename binary (windows)
        if: matrix.platform.os_name == 'Windows-x86_64'
        working-directory: mekadb
        run: mv target/${{ matrix.platform.target }}/release/mekadbms.exe target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}

      - name: Rename binary (linux and macos)
        working-directory: mekadb
        if: matrix.platform.os_name != 'Windows-x86_64'
        run: mv target/${{ matrix.platform.target }}/release/mekadbms target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}

      - name: Generate SHA-256
        working-directory: mekadb
        run: shasum -a 256 target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }} | cut -d ' ' -f 1 > target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}.sha256

      - name: Show bins
        working-directory: mekadb
        run: tree -hDR target

      - name: Release binary and SHA-256 checksum to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >-
            gh release edit ${{ steps.meta.outputs.version }}
            "target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}#${{ matrix.platform.bin }}"
            "target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}.sha256#${{ matrix.platform.bin }}"
            --draft           
            --generate-notes
            --title "Version ${{ steps.meta.outputs.version }}"
#        with:
#          tag_name: ${{ steps.params.outputs.mekadbTag }}
#          token: ${{ secrets.GITHUB_TOKEN }}
#          files: |
#            target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}
#            target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}.sha256
